version: '3.6'
services:
    nginx:
        build: ./nginx
        container_name: nginx
        environment:
            - SERVER_NAME=${SERVER_NAME}
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./../:/var/www
        ports:
            - 80:80
        links:
            - php-fpm
        networks:
            - ok_dev
        restart: always
    php-fpm:
        build: ./php-fpm
        container_name: php-fpm
        volumes:
            - ./../:/var/www
            - ./logs/php:/var/log/php
            - ./logs/xdebug:/var/log/xdebug
            - ./data/session:/var/lib/php/session
        environment:
            - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        ports:
            - 9000:9000
            - 8307:8307
            - 8707:8707
        links:
            - mailtrap
            - memcached
            - redis
        networks:
            - ok_dev
    mailtrap:
        image: schickling/mailcatcher:latest
        container_name: mailtrap
        networks:
            - ok_dev
        ports:
            - 1025:1025
            - 1080:1080
networks:
    ok_dev:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.0.0/24
